version: "3"

services:
    codotype:
        container_name: codotype-dev
        build: ./
        volumes:
            - /home/aeksco/code/codotype/codotype/packages/generators/codotype-generator-starter-kit:/usr/src/plugin
            - ./.codotype-out:/usr/src/app/.codotype-out
        ports:
            - "8080:8080"
