version: "3"

services:
    codotype:
        container_name: codotype-dev
        build: ./
        volumes:
            - /home/aeksco/code/codotype/codotype/packages/generators/codotype-generator-starter-kit:/usr/src/plugin
        environment:
            - PLUGIN_ABSOLUTE_PATH=/usr/src/plugin
        ports:
            - "8080:8080"
